# Generated by Django 3.1.14 on 2023-02-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20230227_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, default='pokemon_images/No_Image_Available.jpg', null=True, upload_to='pokemon_images'),
        ),
    ]
