# Generated by Django 3.1.14 on 2023-02-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20230227_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, default='No.jpg', null=True, upload_to='pokemon_images'),
        ),
    ]
