# Generated by Django 3.1.14 on 2023-03-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0019_auto_20230302_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, default='No.jpg', null=True, upload_to='pokemon_images'),
        ),
    ]
