# Generated by Django 3.1.14 on 2023-03-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0030_auto_20230302_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default='pokemon_images/No.jpg', null=True, upload_to='pokemon_images', verbose_name='Изображение покемона'),
        ),
    ]
