# Generated by Django 3.1.14 on 2023-03-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0032_auto_20230307_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemonentity',
            options={'verbose_name': 'Pokemon entity', 'verbose_name_plural': 'Pokemon entities'},
        ),
    ]
